Repository nephila/django-meta, pull requests merged in 2019-03, with the labels that each got.

#83 Added support for Django 2.1, 2.2 - Python 3.7
  .travis.yml
  HISTORY.rst
  README.rst
  requirements-docs.txt
  requirements-test.txt
  setup.py
  tox.ini
Labels: type: feature

#72 Support for different titles for each service
  meta/models.py
  meta/templates/meta/meta.html
  meta/views.py
  tests/example_app/migrations/0001_initial.py
  tests/example_app/models.py
  tests/test_meta.py
  tests/test_metadata_mixin.py
  tests/test_mixin.py
Labels: first time, type: feature

#84 Add support for og:image:secure_url
  HISTORY.rst
  docs/settings.rst
  meta/settings.py
  meta/templatetags/meta.py
  tests/test_mixin.py
  tests/test_templatetags.py
Labels: type: bug
